import { DanceClass, StudentChild, Booking, PaymentRecord, Announcement, StudioSettings } from './types';

export const INITIAL_CLASSES: DanceClass[] = [
  {
    id: 'cls-1',
    name: 'Ballet Kids',
    category: 'Kids',
    level: 'Beginner (Ages 6–9)',
    days: 'Mon · Wed · Fri',
    time: '6:00 – 7:00 PM',
    durationMinutes: 60,
    totalSeats: 12,
    enrolledCount: 8,
    monthlyFee: 2000,
    dropInFee: 800,
    instructor: 'Priya Sen',
    icon: '🩰',
    active: true,
  },
  {
    id: 'cls-2',
    name: 'Hip-Hop Teens',
    category: 'Teens',
    level: 'Intermediate (Ages 13–17)',
    days: 'Tue · Thu',
    time: '7:00 – 8:00 PM',
    durationMinutes: 60,
    totalSeats: 10,
    enrolledCount: 10,
    monthlyFee: 2500,
    dropInFee: 900,
    instructor: 'Kabir Khan',
    icon: '🧢',
    active: true,
  },
  {
    id: 'cls-3',
    name: 'Adult Contemporary',
    category: 'Adult',
    level: 'All levels (Ages 18+)',
    days: 'Sat',
    time: '8:00 – 9:30 PM',
    durationMinutes: 90,
    totalSeats: 15,
    enrolledCount: 5,
    monthlyFee: 2200,
    dropInFee: 800,
    instructor: 'Priya Sen',
    icon: '✨',
    active: true,
  },
  {
    id: 'cls-4',
    name: 'Kathak Foundations',
    category: 'Kids',
    level: 'Classical (Ages 7–12)',
    days: 'Tue · Sat',
    time: '5:00 – 6:00 PM',
    durationMinutes: 60,
    totalSeats: 10,
    enrolledCount: 6,
    monthlyFee: 2200,
    dropInFee: 800,
    instructor: 'Ananya Shastri',
    icon: '🪘',
    active: true,
  },
];

export const INITIAL_STUDENTS: StudentChild[] = [
  {
    id: 'stu-1',
    name: 'Ananya Sharma',
    age: 7,
    gender: 'Female',
    category: 'Kids',
    enrolledClass: 'Ballet Kids',
    classId: 'cls-1',
    guardianName: 'Sunita Sharma',
    guardianPhone: '+91 98765 43210',
    feeStatus: 'paid',
    dueAmount: 0,
    avatarColor: 'plum',
    notes: 'Regular student, very attentive. Working on turnout technique.',
  },
  {
    id: 'stu-2',
    name: 'Diya Mehta',
    age: 8,
    gender: 'Female',
    category: 'Kids',
    enrolledClass: 'Ballet Kids',
    classId: 'cls-1',
    guardianName: 'Sunita Sharma',
    guardianPhone: '+91 98765 43210',
    feeStatus: 'due',
    dueAmount: 2000,
    avatarColor: 'gold',
    notes: 'Enrolled early Sept. September monthly fee pending.',
  },
  {
    id: 'stu-3',
    name: 'Rohan Kapoor',
    age: 28,
    gender: 'Male',
    category: 'Adult',
    enrolledClass: 'Adult Contemporary',
    classId: 'cls-3',
    guardianName: 'Self',
    guardianPhone: '+91 98111 22334',
    feeStatus: 'paid',
    dueAmount: 0,
    avatarColor: 'blue',
    notes: 'Drop-in pass subscriber. Excellent flexibility.',
  },
  {
    id: 'stu-4',
    name: 'Kavya R.',
    age: 6,
    gender: 'Female',
    category: 'Kids',
    enrolledClass: 'Ballet Kids',
    classId: 'cls-1',
    guardianName: 'Radha Raman',
    guardianPhone: '+91 99222 33445',
    feeStatus: 'paid',
    dueAmount: 0,
    avatarColor: 'green',
    notes: 'Needs light encouragement with choreography recall.',
  },
  {
    id: 'stu-5',
    name: 'Meera J.',
    age: 7,
    gender: 'Female',
    category: 'Kids',
    enrolledClass: 'Ballet Kids',
    classId: 'cls-1',
    guardianName: 'Jayesh Joshi',
    guardianPhone: '+91 97333 44556',
    feeStatus: 'paid',
    dueAmount: 0,
    avatarColor: 'blue',
  },
  {
    id: 'stu-6',
    name: 'Sneha Nair',
    age: 15,
    gender: 'Female',
    category: 'Teens',
    enrolledClass: 'Hip-Hop Teens',
    classId: 'cls-2',
    guardianName: 'Pradeep Nair',
    guardianPhone: '+91 98444 55667',
    feeStatus: 'due',
    dueAmount: 2500,
    avatarColor: 'gold',
  },
  {
    id: 'stu-7',
    name: 'Aarav Patel',
    age: 14,
    gender: 'Male',
    category: 'Teens',
    enrolledClass: 'Hip-Hop Teens',
    classId: 'cls-2',
    guardianName: 'Hetal Patel',
    guardianPhone: '+91 96555 66778',
    feeStatus: 'due',
    dueAmount: 2500,
    avatarColor: 'plum',
  },
  {
    id: 'stu-8',
    name: 'Tanya Verma',
    age: 24,
    gender: 'Female',
    category: 'Adult',
    enrolledClass: 'Adult Contemporary',
    classId: 'cls-3',
    guardianName: 'Self',
    guardianPhone: '+91 95666 77889',
    feeStatus: 'due',
    dueAmount: 800,
    avatarColor: 'gold',
  },
];

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: 'bk-1',
    classId: 'cls-1',
    className: 'Ballet Kids',
    studentName: 'Ananya Sharma',
    childId: 'stu-1',
    dateTime: '2026-09-18T18:00:00',
    timeStr: '6:00 – 7:00 PM',
    dateStr: 'Today · Tue 18 Sep',
    status: 'booked',
    fee: 800,
  },
  {
    id: 'bk-2',
    classId: 'cls-1',
    className: 'Ballet Kids',
    studentName: 'Diya Mehta',
    childId: 'stu-2',
    dateTime: '2026-09-21T18:00:00',
    timeStr: '6:00 – 7:00 PM',
    dateStr: 'Fri 21 Sep',
    status: 'booked',
    fee: 800,
  },
  {
    id: 'bk-3',
    classId: 'cls-2',
    className: 'Hip-Hop Teens',
    studentName: 'Ananya Sharma',
    childId: 'stu-1',
    dateTime: '2026-09-18T19:00:00',
    timeStr: '7:00 – 8:00 PM',
    dateStr: 'Tue 18 Sep',
    status: 'waitlist',
    waitlistPos: 2,
    fee: 900,
  },
  {
    id: 'bk-4',
    classId: 'cls-1',
    className: 'Ballet Kids',
    studentName: 'Ananya Sharma',
    childId: 'stu-1',
    dateTime: '2026-09-17T18:00:00',
    timeStr: '6:00 – 7:00 PM',
    dateStr: 'Mon 17 Sep',
    status: 'completed',
    attendanceResult: 'present',
    fee: 800,
  },
  {
    id: 'bk-5',
    classId: 'cls-1',
    className: 'Ballet Kids',
    studentName: 'Ananya Sharma',
    childId: 'stu-1',
    dateTime: '2026-09-14T18:00:00',
    timeStr: '6:00 – 7:00 PM',
    dateStr: 'Fri 14 Sep',
    status: 'completed',
    attendanceResult: 'absent',
    fee: 800,
  },
];

export const INITIAL_PAYMENTS: PaymentRecord[] = [
  {
    id: 'pay-1',
    studentId: 'stu-1',
    studentName: 'Ananya Sharma',
    amount: 2000,
    method: 'UPI',
    status: 'Paid',
    note: 'September monthly fees',
    date: '10 Sep 2026',
  },
  {
    id: 'pay-2',
    studentId: 'stu-3',
    studentName: 'Rohan Kapoor',
    amount: 2400,
    method: 'UPI',
    status: 'Paid',
    note: '3 class bundle',
    date: '12 Sep 2026',
  },
  {
    id: 'pay-3',
    studentId: 'stu-4',
    studentName: 'Kavya R.',
    amount: 2000,
    method: 'Cash',
    status: 'Paid',
    note: 'September fee - Studio desk',
    date: '15 Sep 2026',
  },
  {
    id: 'pay-4',
    studentId: 'stu-5',
    studentName: 'Meera J.',
    amount: 2000,
    method: 'Bank',
    status: 'Paid',
    note: 'September bank transfer',
    date: '16 Sep 2026',
  },
  {
    id: 'pay-5',
    studentId: 'stu-1',
    studentName: 'Ananya Sharma',
    amount: 2000,
    method: 'UPI',
    status: 'Paid',
    note: 'August monthly fees',
    date: '10 Aug 2026',
  },
  {
    id: 'pay-6',
    studentId: 'stu-2',
    studentName: 'Diya Mehta',
    amount: 2000,
    method: 'Cash',
    status: 'Paid',
    note: 'July fees',
    date: '12 Jul 2026',
  },
];

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'ann-1',
    title: 'Ballet Kids starts in 2 hours',
    body: 'Reminder for Ananya Sharma: Please bring soft ballet slippers and water bottle. Class begins at 6:00 PM.',
    target: 'Kids',
    date: 'Today · 4:00 PM',
    read: false,
    type: 'reminder',
    tag: 'Reminder',
  },
  {
    id: 'ann-2',
    title: 'Annual Recital practice starts next week',
    body: 'All students are invited to join our winter recital showcase preparation! Practice schedule will be shared in class.',
    target: 'All students',
    date: 'Yesterday · 11:30 AM',
    read: false,
    type: 'announcement',
    tag: 'Announcement',
  },
  {
    id: 'ann-3',
    title: 'Booking confirmed: Ballet Kids',
    body: 'Seat secured for Diya Mehta on Fri 21 Sep at 6:00 PM. We look forward to seeing you on the dance floor!',
    target: 'Kids',
    date: 'Yesterday · 9:15 AM',
    read: true,
    type: 'booking',
    tag: 'Booking',
  },
  {
    id: 'ann-4',
    title: 'September fees reminder',
    body: 'Friendly reminder: Monthly dues for September are due by the 20th. You can settle via UPI or at the studio front desk.',
    target: 'All students',
    date: '3 days ago',
    read: true,
    type: 'payment',
    tag: 'Fee Due',
  },
  {
    id: 'ann-5',
    title: 'New class: Adult Contemporary on Saturdays',
    body: 'Excited to announce our new weekend Adult Contemporary batch with Priya Sen. 15 spots open for drop-in or monthly enrollment.',
    target: 'Adult',
    date: '5 days ago',
    read: true,
    type: 'announcement',
    tag: 'New Batch',
  },
];

export const INITIAL_SETTINGS: StudioSettings = {
  studioName: 'Huaid Dance World',
  ownerName: 'Priya Sen',
  ownerPhone: '+91 98765 00000',
  upiId: 'nritya@upi',
  cancellationWindowHours: 4,
  reminderBeforeHours: 2,
  pushNotifications: true,
  paymentClaimAlerts: true,
};
